version: '3.7'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  db_data:
    name: ${VOLUME_DB_ID}

services:
  nginx:
    image: hexbatch_dev/nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
        - APP_GROUP=${APP_GROUP}
        - APP_GROUP_ID=${APP_GROUP_ID}
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
        - TZ=${TIMEZONE}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    networks:
      backend:
        aliases:
          - ${APP_HOST}

  php-fpm:
    image: hexbatch_dev/php-fpm
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
      args:
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
        - APP_GROUP=${APP_GROUP}
        - APP_GROUP_ID=${APP_GROUP_ID}
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
        - TARGET_PHP_VERSION=${PHP_VERSION}
        - TZ=${TIMEZONE}
    environment:
      - GK_MYSQL_DATABASE=${DB_MYSQL_DATABASE}
      - GK_MYSQL_USER=${DB_MYSQL_USER}
      - GK_MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}
      - GK_MYSQL_PORT=${DB_MYSQL_OWNPORT}
      - GK_MYSQL_CHARSET=${DB_MYSQL_CHARSET}
      - GK_MYSQL_HOST=db
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    networks:
      - backend


  db:
    image: mysql:latest

    #allow user to create triggers and procedures
    command: --log_bin_trust_function_creators=1
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_MYSQL_DATABASE}"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "${DB_MYSQL_USER}"
      # You can use whatever password you like
      MYSQL_PASSWORD: "${DB_MYSQL_PASSWORD}"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "${DB_MYSQL_ROOTPASSWORD}"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "${DB_MYSQL_HOSTPORT}:${DB_MYSQL_OWNPORT}"
    expose:
      # Opens port 3306 on the container
      - "${DB_MYSQL_OWNPORT}"
      # Where our data will be persisted
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "${DB_MYSQL_ROOTPASSWORD}"
    networks:
      - backend
      
  phinx:    
    image: hexbatch_dev/phinx
    build:
      context: .
      dockerfile: ./phinx/Dockerfile
    depends_on:
      - db
    environment:
      - PHINX_DBNAME=${DB_MYSQL_DATABASE}
      - PHINX_DBUSER=${DB_MYSQL_USER}
      - PHINX_DBPASS=${DB_MYSQL_PASSWORD}
      - GK_MYSQL_PORT=${DB_MYSQL_OWNPORT}
      - PHINX_DBHOST=db
    networks:
      - backend

  doxygen:
    image: hexbatch_dev/doxygen
    build:
      context: .
      dockerfile: ./doxygen/Dockerfile
    networks:
      - backend

  cpp:
    image: hexbatch_dev/cpp
    build:
      context: .
      dockerfile: ./cpp/Dockerfile
    networks:
      - backend